#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
main_file="$root/src/main.cpp"
header_file="$root/src/ofApp.h"
app_file="$root/src/ofApp.cpp"
workflow_file="$root/.github/workflows/deploy.yml"
font_file="$root/bin/data/fonts/CaslonCPswash.otf"
secondary_font_file="$root/bin/data/fonts/Arial.ttf"
addons_file="$root/addons.make"

test -s "$font_file"
test -s "$secondary_font_file"

grep -Eq 'settings\.setSize\(1024,[[:space:]]*768\)' "$main_file"
! grep -Eq 'settings\.setSize\(1920,[[:space:]]*1080\)' "$main_file"

grep -Eq 'bool[[:space:]]+startScreenActive[[:space:]]*=[[:space:]]*true' "$header_file"
grep -Eq 'struct[[:space:]]+Scene' "$header_file"
grep -Eq 'std::vector<Scene>[[:space:]]+scenes' "$header_file"
grep -Eq 'int[[:space:]]+currentScene' "$header_file"
grep -Eq 'ofRectangle[[:space:]]+startButtonBounds' "$header_file"
grep -Eq 'ofTrueTypeFont[[:space:]]+startTitleFont' "$header_file"
grep -Eq 'ofTrueTypeFont[[:space:]]+startPromptFont' "$header_file"
grep -Eq 'void[[:space:]]+configurarPantallaInicio\(\)' "$header_file"
grep -Eq 'void[[:space:]]+dibujarPantallaInicio\(\)' "$header_file"
grep -Eq 'void[[:space:]]+dibujarEscenaActual\(\)' "$header_file"
grep -Eq 'void[[:space:]]+avanzarEscena\(\)' "$header_file"
! grep -Eq 'ofVideoGrabber|ofxCvHaarFinder|ofxSvg|ofShader|ofFbo|Spiral|Star' "$header_file"

grep -Eq 'CaslonCPswash\.otf' "$app_file"
grep -Eq 'Arial\.ttf' "$app_file"
grep -Eq 'ofTrueTypeFontSettings[[:space:]]+titleSettings' "$app_file"
grep -Eq 'ofTrueTypeFontSettings[[:space:]]+promptSettings' "$app_file"
grep -Eq 'addRanges\(ofAlphabet::Latin\)' "$app_file"
grep -Eq 'ofUTF8Iterator' "$app_file"
grep -Eq 'ofUTF8ToString' "$app_file"
grep -Eq 'drawAnimatedTextCentered' "$app_file"
grep -Eq 'void ofApp::dibujarPantallaInicio\(\)' "$app_file"
grep -Eq 'Prueba Camara|Prueba Cámara' "$app_file"
grep -Eq 'Empezar' "$app_file"
! grep -Eq 'Apreta|Apretá|para empezar|Enter' "$app_file"
grep -Eq 'pulse' "$app_file"
grep -Eq 'startButtonBounds\.inside' "$app_file"
grep -Eq 'void ofApp::mousePressed' "$app_file"
grep -Eq 'startScreenActive[[:space:]]*=[[:space:]]*false' "$app_file"
grep -Eq 'scenes[[:space:]]*=[[:space:]]*\{\{' "$app_file"
grep -Eq 'Escena 1' "$app_file"
grep -Eq 'Escena 2' "$app_file"
grep -Eq 'Escena 3' "$app_file"
grep -Eq 'APP_H[[:space:]]*-[[:space:]]*96\.0f|APP_H[[:space:]]*\*[[:space:]]*0\.86f' "$app_file"
grep -Eq 'APP_W[[:space:]]*=[[:space:]]*1024' "$app_file"
grep -Eq 'APP_H[[:space:]]*=[[:space:]]*768' "$app_file"
! grep -Eq 'path144|ofVideoGrabber|Haar|SVG_W|SVG_H|dibujarPatron|dibujarCaja|dibujarEstrellas|dibujarEspirales|dibujarHUD' "$app_file"

! grep -Eq '^ofx(OpenCv|Svg)$' "$addons_file"
grep -Eq 'branches:[[:space:]]*\[[[:space:]]*main[[:space:]]*\]' "$workflow_file"
! grep -Eq 'branches:[[:space:]]*\[[^]]*demo[^]]*\]' "$workflow_file"
