#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
main_file="$root/src/main.cpp"
header_file="$root/src/ofApp.h"
app_file="$root/src/ofApp.cpp"
workflow_file="$root/.github/workflows/deploy.yml"
font_file="$root/bin/data/fonts/CaslonCPswash.otf"
secondary_font_file="$root/bin/data/fonts/Arial.ttf"
addons_file="$root/addons.make"

test -s "$font_file"
test -s "$secondary_font_file"

style_doc="$root/docs/tipo-codigo-timber.md"

test -s "$style_doc"
grep -Eq 'timber_parte_2/05_incremento_barra_tiempo' "$style_doc"
grep -Eq 'ofVec2f' "$style_doc"
grep -Eq 'stringWidth' "$style_doc"
grep -Eq 'arreglos fijos' "$style_doc"
grep -Eq 'No usar' "$style_doc"

grep -Eq 'settings\.setSize\(960,[[:space:]]*540\)' "$main_file"
! grep -Eq 'settings\.setSize\(1024,[[:space:]]*768\)' "$main_file"
! grep -Eq 'settings\.setSize\(1920,[[:space:]]*1080\)' "$main_file"

grep -Eq 'bool[[:space:]]+startScreenActive[[:space:]]*=[[:space:]]*true' "$header_file"
grep -Eq 'float[[:space:]]+ancho[[:space:]]*=[[:space:]]*1920' "$header_file"
grep -Eq 'float[[:space:]]+alto[[:space:]]*=[[:space:]]*1080' "$header_file"
grep -Eq 'bool[[:space:]]+pantalla_completa' "$header_file"
grep -Eq 'int[[:space:]]+escena_actual' "$header_file"
grep -Eq 'string[[:space:]]+titulos_escenas\[4\]' "$header_file"
grep -Eq 'string[[:space:]]+textos_escenas\[4\]' "$header_file"
grep -Eq 'string[[:space:]]+noticias_apuestas\[3\]' "$header_file"
grep -Eq 'string[[:space:]]+mensajes_chat\[6\]' "$header_file"
grep -Eq 'string[[:space:]]+titulo_letras\[20\]' "$header_file"
grep -Eq 'float[[:space:]]+alpha_letras\[20\]' "$header_file"
grep -Eq 'ofVec2f[[:space:]]+posicion_boton' "$header_file"
grep -Eq 'ofTrueTypeFont[[:space:]]+fuente_titulo' "$header_file"
grep -Eq 'ofTrueTypeFont[[:space:]]+fuente_titulo_fallback' "$header_file"
grep -Eq 'ofTrueTypeFont[[:space:]]+fuente_texto' "$header_file"
grep -Eq 'void[[:space:]]+dibujarPantallaInicio\(\)' "$header_file"
grep -Eq 'void[[:space:]]+dibujarEscenaActual\(\)' "$header_file"
grep -Eq 'void[[:space:]]+dibujarInterfazApuestas\(\)' "$header_file"
grep -Eq 'void[[:space:]]+dibujarTextoConFallback\(string[[:space:]]+texto,[[:space:]]*float[[:space:]]+x,[[:space:]]*float[[:space:]]+y,[[:space:]]*float[[:space:]]+alpha\)' "$header_file"
grep -Eq 'float[[:space:]]+anchoTextoConFallback\(string[[:space:]]+texto\)' "$header_file"
grep -Eq 'void[[:space:]]+avanzarEscena\(\)' "$header_file"
grep -Eq 'No esta en el md: eventos de mouse extra' "$header_file"
! grep -Eq 'private:|struct[[:space:]]+Scene|std::vector|ofRectangle|glm::vec2' "$header_file"
! grep -Eq 'ofVideoGrabber|ofxCvHaarFinder|ofxSvg|ofShader|ofFbo|Spiral|Star' "$header_file"

grep -Eq 'No esta en el md: ofSetWindowTitle' "$app_file"
grep -Eq 'No esta en el md: ofSetFrameRate' "$app_file"
grep -Eq 'No esta en el md: ofBackground' "$app_file"
grep -Eq 'No esta en el md: ofGetWidth' "$app_file"
grep -Eq 'No esta en el md: .*ofGetHeight' "$app_file"
grep -Eq 'No esta en el md: ofSetLineWidth' "$app_file"
grep -Eq 'No esta en el md: length\(\)' "$app_file"
grep -Eq 'No esta en el md: substr\(\)' "$app_file"
grep -Eq 'No esta en el md: return' "$app_file"
grep -Eq 'CaslonCPswash\.otf' "$app_file"
grep -Eq 'Arial\.ttf' "$app_file"
grep -Eq 'fuente_titulo\.load\("fonts/CaslonCPswash\.otf",[[:space:]]*70,[[:space:]]*true,[[:space:]]*true\)' "$app_file"
grep -Eq 'fuente_titulo_fallback\.load\("fonts/Arial\.ttf",[[:space:]]*70,[[:space:]]*true,[[:space:]]*true\)' "$app_file"
grep -Eq 'fuente_texto\.load\("fonts/Arial\.ttf",[[:space:]]*40,[[:space:]]*true,[[:space:]]*true\)' "$app_file"
grep -Eq 'fuente_texto_chico\.load\("fonts/Arial\.ttf",[[:space:]]*25,[[:space:]]*true,[[:space:]]*true\)' "$app_file"
grep -Eq 'stringWidth' "$app_file"
grep -Eq 'drawString' "$app_file"
grep -Eq 'ofDrawRectangle' "$app_file"
grep -Eq 'ofDrawLine' "$app_file"
grep -Eq 'for[[:space:]]*\(int[[:space:]]+i[[:space:]]*=[[:space:]]*0;[[:space:]]*i[[:space:]]*<[[:space:]]*80;[[:space:]]*i\+\+\)' "$app_file"
grep -Eq 'ofDrawLine\(x_1,[[:space:]]*y_1,[[:space:]]*x_2,[[:space:]]*y_2\)' "$app_file"
grep -Eq 'float[[:space:]]+escala_x[[:space:]]*=[[:space:]]*ofGetWidth\(\)[[:space:]]*/[[:space:]]*ancho' "$app_file"
grep -Eq 'float[[:space:]]+escala_y[[:space:]]*=[[:space:]]*ofGetHeight\(\)[[:space:]]*/[[:space:]]*alto' "$app_file"
grep -Eq 'ofScale\(escala_x,[[:space:]]*escala_y\)' "$app_file"
grep -Eq 'void ofApp::dibujarPantallaInicio\(\)' "$app_file"
grep -Eq 'Prueba Camara|Prueba Cámara' "$app_file"
grep -Eq 'Empezar' "$app_file"
! grep -Eq 'Apreta|Apretá|para empezar|Enter' "$app_file"
grep -Eq 'alpha_boton' "$app_file"
grep -Eq 'x[[:space:]]*=[[:space:]]*x[[:space:]]*/[[:space:]]*escala_x' "$app_file"
grep -Eq 'y[[:space:]]*=[[:space:]]*y[[:space:]]*/[[:space:]]*escala_y' "$app_file"
grep -Eq 'x[[:space:]]*>=[[:space:]]*posicion_boton\.x' "$app_file"
grep -Eq 'void ofApp::mousePressed' "$app_file"
grep -Eq 'startScreenActive[[:space:]]*=[[:space:]]*false' "$app_file"
grep -Eq 'titulos_escenas\[0\][[:space:]]*=[[:space:]]*"Escena 1"' "$app_file"
grep -Eq 'titulos_escenas\[1\][[:space:]]*=[[:space:]]*"Escena 2"' "$app_file"
grep -Eq 'titulos_escenas\[2\][[:space:]]*=[[:space:]]*"Escena 3"' "$app_file"
grep -Eq 'titulos_escenas\[3\][[:space:]]*=[[:space:]]*"Interfaz de apuestas"' "$app_file"
grep -Eq 'Escena 1' "$app_file"
grep -Eq 'Escena 2' "$app_file"
grep -Eq 'Escena 3' "$app_file"
grep -Eq 'Interfaz de apuestas' "$app_file"
grep -Eq 'Ganadores de apuestas|Noticias generales|Tragedias relacionadas' "$app_file"
grep -Eq 'Chat automatizado|Presentador|Entrada|Salida|Siguiente|Anterior' "$app_file"
grep -Eq 'float[[:space:]]+y_valor[[:space:]]*=[[:space:]]*x_valor[[:space:]]*\*[[:space:]]*x_valor' "$app_file"
grep -Eq 'fuente_titulo_fallback\.drawString\(letra' "$app_file"
grep -Eq 'letra[[:space:]]*==[[:space:]]*"á"|letra[[:space:]]*==[[:space:]]*"é"|letra[[:space:]]*==[[:space:]]*"1"' "$app_file"
grep -Eq 'alto[[:space:]]*-[[:space:]]*160' "$app_file"
! grep -Eq 'namespace|ofTrueTypeFontSettings|ofUTF8Iterator|ofUTF8ToString|std::vector|ofRectangle|glm::vec2|ofDrawRectRounded|ofPushMatrix|ofTranslate|ofLerp|getStringBoundingBox' "$app_file"
! grep -Eq 'ofBeginShape|ofVertex|ofEndShape|path144|ofVideoGrabber|Haar|SVG_W|SVG_H|dibujarPatron|dibujarCaja|dibujarEstrellas|dibujarEspirales|dibujarHUD' "$app_file"

! grep -Eq '^ofx(OpenCv|Svg)$' "$addons_file"
grep -Eq 'branches:[[:space:]]*\[[[:space:]]*main[[:space:]]*\]' "$workflow_file"
! grep -Eq 'branches:[[:space:]]*\[[^]]*demo[^]]*\]' "$workflow_file"
